language: node_js
sudo: false
maximum_number_of_builds: 1
node_js:
  - '6'
after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
